### ISSUE TITLE
Mobile back-end: able to create observations

### ISSUE THREAD

**Issue by noffle** [osmlab/field-data-collection#101]
- [x] Figure out how new node creation + sync + OSM.org submission will work
- [x] Function: creates a new observation (/w device-id, timestamp, and preset-id)
- [x] ^ Add option to create on-demand feature as well

**Comment by sethvincent** [comment]
@noffle I'm not seeing where this function lives: `Function: creates a new observation (/w device-id, timestamp, and preset-id)`.

I'd expect the device id and timestamp at least to be part of https://github.com/osmlab/field-data-collection/blob/master/app/lib/osm-p2p.js#L64

**Comment by noffle** [comment]
They'd be passed in as GeoJSON feature properties (which get translated into OSM "tags").
