### ISSUE TITLE
Coordinator: serve survey defs over HTTP+JSON

### ISSUE THREAD

**Issue by noffle** [osmlab/field-data-collection#102]
The coordinator app will run a tiny HTTP server that the mobile app can use to ask it "what survey definitions do you have?" and "give me this survey definition".

- [x] `GET /surveys` route (JSON response)
- [x] `GET /survey/:id` route (raw gzipped tarball)

**Comment by dereklieu** [comment]
Coordinator app currently surfaces an express server that has observation creation/list routes. You can add new routes [here](https://github.com/osmlab/field-data-coordinator/blob/master/lib/server.js).

**Comment by noffle** [comment]
Thanks Derek.

What do you think about where the survey definition tarballs will be served from? Will the user import these definitions in from their computer, or from some pre-defined path that the app needs to know about? cc @felskia

**Comment by dereklieu** [comment]
I think the idea is to have the user upload them from their local filesystem. @felskia does that sound right?

**Comment by mojodna** [comment]
Input for the survey definition compilation process is a directory containing a YAML survey definition and a pile of presets + fields as directories and JSON files (essentially: copies of default iD presets, pruned to only include types + fields referenced in the survey definition and with fields modified).

**Comment by noffle** [comment]
@mojodna For the sake of getting a list of available survey defs, it'll be a matter of just scanning some `%APPDATA%/surveys/` dir for `.tgz` files?

**Comment by mojodna** [comment]
Yup.
