### ISSUE TITLE
Surveys Page

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#136]
@mojodna For this page can we take away the refresh surveys button and go with the flow we outlined before which is:

- Have OSM on there all the time
- Click Add New Surveys > See list of surveys they can add > click on surveys they want to add > press submit to add them. 

I just added the modal up there now. Let me know what you think.

**Comment by mojodna** [comment]
OSM is temporarily stubbed in; we'll want to ship a survey with all of the iD presets available.

![screenshot_1498693824](https://user-images.githubusercontent.com/45/27665417-e3a80d6e-5c21-11e7-9c38-40bf38b6602d.png)

The "ADD NEW SURVEYS" button currently obscures information about the number of observations associated with the last survey. I don't know enough about RN layout, so I'd like to tag @sethvincent to have a look at fixing that. There's a TODO in `app/screens/account/surveys.js` for it.

We should probably add the ability to delete surveys (slide, then confirm?) to this screen as well.

![screenshot_1498693805](https://user-images.githubusercontent.com/45/27665418-e3aa6712-5c21-11e7-8ae4-62be421f5d57.png)

There's an un-styled status bar that appears at the top of this screen indicating the current status of discovering / downloading survey definitions.

This is currently implemented where touching the name of the survey will download it immediately (hence the change from "SUBMIT" to "DONE"). This was easiest given the plumbing that already existed, but we can change it to select and download in bulk (again, @sethvincent / @felskia for the styling of selected surveys).

We should also include indications for when surveys have already been downloaded.

**Comment by mojodna** [comment]
Here's the status bar in action:

![screenshot_1498694264](https://user-images.githubusercontent.com/45/27665598-eed38bf4-5c22-11e7-9de5-0d4e88714768.png)
