### ISSUE TITLE
data sync errors

### ISSUE THREAD

**Issue by sethvincent** [osmlab/field-data-collection#180]
During use there are still situations where there are errors during OSM data sync.

Usually this happens with larger areas (minimum of 5-10 city blocks), while smaller areas (1-2 city blocks) work fine.

It's hard to pin down the errors, but what typically happens for me is:

```
'Unhandled promise rejection', { [Error: write callback called multiple times]
```

Sometimes followed by a full crash of the app.

**Comment by noffle** [comment]
I wonder if this is OSM.org returning errors about the dataset being too large to download.

**Comment by dereklieu** [comment]
This is on the mobile app side right? And you've confirmed that whatever data you've synced in the coordinator is actual osm xml and not an osm.org error? (which the coordinator should report)

**Comment by noffle** [comment]
Oh derp, you're right @dereklieu. Don't mind me.

**Comment by sethvincent** [comment]
Yeah, this is the import from the coordinator app to the mobile app. The coordinator app downloads the data ok.

**Comment by noffle** [comment]
This "fast sync" hack I put in was well intentioned, but I can see it's causing lots of problems and it's sucked up a LOT of dev time (maybe not just mine, either). I'm wondering if it's worth using the regular osm-p2p-db replication mechanism for sync instead. Downside: it's a fair bit slower. Upside: it *works* and can be relied on.
