### ISSUE TITLE
Add toggles to surveys page

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#182]
There should only be one on at a time. Functionality should work like this: 

- Survey is only active when user toggles it on
- One survey should always be active. So if the user tries to toggle off both, an error should appear.

**Comment by kamicut** [comment]
@felskia What happens to the observations belonging to inactive surveys:
1. Show them but don't allow to edit them
2. Don't show them

**Comment by felskia** [comment]
@kamicut 
<img width="275" alt="screen shot 2017-09-20 at 11 51 49 am" src="https://user-images.githubusercontent.com/5421566/30653815-1e89e302-9dfa-11e7-8a56-d97941181f78.png">
