### ISSUE TITLE
Be able to click on OSM features

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#189]
We should have an active state when clicking on a feature. 

@sethvincent do you want to do this first since you're adding in OSM features and I can then go in and style? Or let me know if it would be easier for me to provide you with styles.

**Comment by sethvincent** [comment]
I think providing the styles for this one would be good. Does this show what you mean? https://marvelapp.com/1jgj1ai/screen/29250069

**Comment by felskia** [comment]
@sethvincent I'll put together a super comprehensive sheet :)

**Comment by felskia** [comment]
@sethvincent I actually got rid of the green, remembering what Vivien said about not being able to see it in the sun. Let me know if you have any questions. 

![map-icons-styles](https://user-images.githubusercontent.com/5421566/29285281-fbfb127c-80fb-11e7-9492-610008244fce.jpg)
