### ISSUE TITLE
Prompt to sync with coordinator app when you first enter the app

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#199]
Give the users a hit what they need to be doing. This should send them to the survey page.

**Comment by sethvincent** [comment]
For demo I placed this in the bottom bar. It's a nice place for it as otherwise that bottom bar isn't super useful until survey/osm data is imported.

![screenshot_1504302771](https://user-images.githubusercontent.com/164214/29989032-964ed3e0-8f3e-11e7-8c58-4653b6c2a830.png)
