### ISSUE TITLE
use Dimensions module to determine container View size

### ISSUE THREAD

**Issue by sethvincent** [osmlab/field-data-collection#203]
Some of the heights and widths we're setting for parent containers are wrong for some phones.

We should use the react-native module `Dimensions` to determine heights and widths in most cases.

We already use Dimensions in some places, like the side menu: https://github.com/osmlab/field-data-collection/blob/39cbafd4aa3f975b0f27f347522c4dcfa3ac905b/app/components/side-menu.js

docs: https://facebook.github.io/react-native/docs/dimensions.html

**Comment by mojodna** [comment]
E.g., on a BLU Advance 5.1:

![image](https://user-images.githubusercontent.com/45/29846985-39327882-8cce-11e7-8f7b-2b8feb343dc8.png)

**Comment by sethvincent** [comment]
I included a fix for modal width/height in this pr: https://github.com/osmlab/field-data-collection/pull/206

**Comment by mojodna** [comment]
Ah, great.

**Comment by sethvincent** [comment]
I think we've done this in the places it's needed. We can open new issues for more specific instances as they come up.
