### ISSUE TITLE
Choose a location page doesn't work because you can't save it

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#225]
<img width="254" alt="screen shot 2017-09-06 at 3 25 47 pm" src="https://user-images.githubusercontent.com/5421566/30130589-ae4734b0-9317-11e7-8ba3-30ed40cf405f.png">

**Comment by sethvincent** [comment]
fixed in 3ecd72bf2ff1441

The save button was there but something about new styles meant it was hidden below the bottom of the modal.
