### ISSUE TITLE
Android Cannot create a LatLngBounds from 0 items

### ISSUE THREAD

**Issue by sethvincent** [osmlab/field-data-collection#234]
It seems like we've been hitting this issue: https://github.com/mapbox/react-native-mapbox-gl/issues/586

It seems to only happen when we load the app for the very first time.

Basically the map isn't loaded yet and we're trying to perform operations on it.

This open PR to react-native-mapbox-gl tries to address the problem at the java level: https://github.com/mapbox/react-native-mapbox-gl/pull/563 (we may need to merge it into my fork of react-native-mapbox-gl if it works well).

**Comment by kamicut** [comment]
@sethvincent how can I reproduce this?

**Comment by sethvincent** [comment]
It's intermittent. For me it happens only sometimes after installing the app on a device/emulator and loading it for the first time.

**Comment by sethvincent** [comment]
closed by #319
