### ISSUE TITLE
See completeness of observations

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#242]
@kamicut since you don't know the app super well, completeness was shown as you'll see in the below screenshots. 

<img width="284" alt="screen shot 2017-09-08 at 2 50 00 pm" src="https://user-images.githubusercontent.com/5421566/30226724-15e070d0-94a5-11e7-8e0c-5183cbe23662.png">
<img width="261" alt="screen shot 2017-09-08 at 2 50 26 pm" src="https://user-images.githubusercontent.com/5421566/30226725-15e6073e-94a5-11e7-8867-48f85b0af70b.png">

**Comment by kamicut** [comment]
I'll close this once we add completeness to #190

**Comment by kamicut** [comment]
This is done
