### ISSUE TITLE
Adding further metadata for each observation

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#245]
Show metadata around a survey definition. When it was updated, how many are incomplete (this last one would be nice if possible.)

**Comment by kamicut** [comment]
@felskia Is this on the "single survey" page? We can calculate completeness for individual observations but what does "completeness of a survey mean"?

**Comment by felskia** [comment]
So, specific metadata that we had outlined that would be nice. 

**On the cards (map view and also on the secondary point confirmation page)**
- Can we say how far away it is to your location? (this one might be super tricky so understand if we can't do it)
- When it was last updated
- If the observation is complete or not (we have the number of observations on the cards on the map view but need them on the confirmation view)

Ex of what would be nice:
<img width="225" alt="screen shot 2017-09-22 at 10 15 36 am" src="https://user-images.githubusercontent.com/5421566/30749366-242301da-9f81-11e7-9887-e0d6250e9dcf.png">


**My Observation View**
- Also name needs to be changed here but I will put this in a new ticket
- Needs what survey it is for

**Observation View**
- what survey it is for (in the blue section)
- when it was updated (in the blue section)
- Survey definition should not be in the header but above Basic Info
