### ISSUE TITLE
Metadata on observations in my observations is wrong

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#247]
Location is not what is saved and the date and time is wrong. Can understand if it's just the emulator working off of west coast time but shouldn't the date be right? 

<img width="251" alt="screen shot 2017-09-11 at 10 02 53 am" src="https://user-images.githubusercontent.com/5421566/30278787-6e346120-96d9-11e7-91ed-41903ead75b2.png">

**Comment by kamicut** [comment]
Is this closed @sethvincent ?
