### ISSUE TITLE
ensure there's a lat/lon when observation is saved

### ISSUE THREAD

**Issue by sethvincent** [osmlab/field-data-collection#248]
In the rare case an observation doesn't have a lat/lon, we should use the react-native `Alert` component to notify user before saving.

As it is now, I think the only way this might come up is if someone chose the "adding a new point" button and then never pressed "add location" on the observation view screen.

The check for lat/lon and `Alert` usage would go here: https://github.com/osmlab/field-data-collection/blob/master/app/screens/Observation/view.js#L94

**Comment by kamicut** [comment]
Closed with #255
