### ISSUE TITLE
syncing data via websockets

### ISSUE THREAD

**Issue by sethvincent** [osmlab/field-data-collection#56]
In the [replication branch](https://github.com/osmlab/field-data-collection/tree/replication) I've got an initial implementation of syncing data via websockets started.

(I chose websockets to start with as it's mentioned as something [react-native supports in their docs](https://facebook.github.io/react-native/docs/network.html))

Mobile app code: https://github.com/osmlab/field-data-collection/blob/replication/app/lib/sync-data.js

Example server to sync with: https://github.com/osmlab/field-data-collection/blob/replication/tools/bin/start-server.js

Right now during replication the server logs an error from protocol-buffers via hyperlog: "Decoded message is not valid"

The initial data coming from the hyperlog in the mobile app looks like this when I do `logstream.on('data', console.log)`:

```
{ '0': 3 }
{ '0': 0, '1': 8, '2': 1 }
{ '0': 1 }
{ '0': 4 }
```

I haven't found the source of the issue yet.

**Comment by gmaclennan** [comment]
Maybe try without `level-party` - I'm not sure how it might affect things, but at least to remove a possible factor.

**Comment by sethvincent** [comment]
Got this branch working: https://github.com/osmlab/field-data-collection/tree/websockets

Right now it's just example code.

It most likely was the upgrade to react-native 0.45 that got it working.

React native example: https://github.com/osmlab/field-data-collection/blob/websockets/app/screens/Account/add-survey.js

Server example: https://github.com/osmlab/field-data-collection/blob/websockets/tools/bin/websocket-server.js

**Comment by noffle** [comment]
That's great news. Nice work!

**Comment by noffle** [comment]
@sethvincent fixed this -- woo. :tada:
