### ISSUE TITLE
use a material design component library

### ISSUE THREAD

**Issue by sethvincent** [osmlab/field-data-collection#57]
Some options:

- https://github.com/react-native-material-design/react-native-material-design
- https://github.com/xinthink/react-native-material-kit
- https://github.com/xotahal/react-native-material-ui
- https://github.com/binggg/mrn

**Comment by mojodna** [comment]
https://github.com/xinthink/react-native-material-kit is the only one of these that includes text controls, so I'd start there and pull in pieces from the others if we're unhappy with the quality of what's included (or need things that aren't bundled).

**Comment by sethvincent** [comment]
Using react-native-material kit and building on top of it when needed: https://github.com/osmlab/field-data-collection/pull/105

**Comment by sethvincent** [comment]
Turns out react-native-material-kit hasn't been updated for react v16 and maintainers have decided to work on a new material design project: https://github.com/material-native/material-native

Discovered this when I merged master into the observations-ui branch earlier.

I'm now inclined to just use bits and pieces of these projects as inspiration and not rely on them as dependencies.

**Comment by sethvincent** [comment]
after looking again at options it seems best to do as I mentioned in the last comment, to grab parts of material-ui libraries that look useful without directly relying on them as dependencies.
