### ISSUE TITLE
P2P Sync: Coordinator <=> Mobile

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#66]

**Comment by noffle** [comment]
- [ ] Investigate whether, given an "average" OSM dataset, sync will be prohibitively slow
- [ ] Write an inner module that does mDNS broadcast+discovery and observation/survey sync
(maybe it just manages/tracks peers?)
- [ ] Write function that, given a peer target (mdns peer instance or ip:port), does an osm-p2p-db sync of observations

**Comment by noffle** [comment]
Performance findings on some datasets:

| filename | file size (XML) | import time | sync time
| --- | --- | --- | --- |
| area | 1 mb | 4s | 30s
| smaller | 1.4 mb | 5s | 47s
| euro | 6.8 mb | 17s | 267s (4.5 mins)
| london | 14 mb | 36s | 640s (10.5 mins)
| lilongwe | 185 mb | 228s | ???s

**Comment by noffle** [comment]
Finished, once https://github.com/osmlab/field-data-collection/issues/168 is resolved.
