### ISSUE TITLE
coordinator app: produce and host survey definition tarball

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#74]

**Comment by mojodna** [comment]
Begun in https://github.com/osmlab/field-data-coordinator/commit/6d0c7b7b5fc86e9bf99d84168d87c73bed58aebf and https://github.com/osmlab/field-data-coordinator/commit/017b44620fa0beaa47d61531c19b96d8099a4e0f

**Comment by mojodna** [comment]
See https://github.com/digidem/mapeo-settings-builder for categorization (#62, #63) + icon handling.
