### ISSUE TITLE
research functionality needed in react-native-mapbox-gl

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#96]

**Comment by gmaclennan** [comment]
Initial findings:

- [`react-native-mapbox-gl`](https://github.com/mapbox/react-native-mapbox-gl) currently uses v4.2.2 which may be missing several key features in [v5.0.2](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CHANGELOG.md)
- It may not be beyond our (Seth's) ability to wrap the latest SDK for react-native / fork the `react-native-mapbox-gl` module: https://facebook.github.io/react-native/docs/native-components-android.html
- There are two ways to add GeoJSON to the map via the SDK: [adding a GeoJSON source](https://www.mapbox.com/android-sdk/examples/add-a-geojson-line/) and [adding an annotation](https://www.mapbox.com/android-sdk/examples/geojson/)
- I am not clear about the performance of large GeoJSON annotations, or the difference with a source. Can somebody ask Mapbox?
- `react-native-mapbox-gl` currently only supports adding GeoJSON, it does not expose any of the source methods
- The SDK has the [necessary methods](https://www.mapbox.com/android-sdk/examples/change-a-layer-color/) for changing attributes of the style, which we would need for the filtering functionality, but these are not currently exposed via `react-native-mapbox-gl`.
- It seems like the only way to currently set a style is via a URL, which means that we would need a local server if we wanted offline, but we could work with an online style for now. It looks like there is active development to be able to pass a style object - another question for Mapbox.

**Comment by 1ec5** [comment]
Hi, I randomly came across this issue. 👋 As an OSM contributor, I’m excited to see this project get off the ground! I’m not very familiar with React Native, but I work on the native Mapbox iOS SDK and happen to have the answers to these particular questions.

> There are two ways to add GeoJSON to the map via the SDK: [adding a GeoJSON source](https://www.mapbox.com/android-sdk/examples/add-a-geojson-line/) and [adding an annotation](https://www.mapbox.com/android-sdk/examples/geojson/)

Indeed, the native Android and iOS SDKs do support adding both shape annotations and GeoJSON sources (known as shape sources on iOS). The latter API is older and is intended to be similar to overlay APIs in Google Maps and Apple’s MapKit. Here’s a bit more information about the different options (geared towards iOS):

https://www.mapbox.com/ios-sdk/api/3.5.4/working-with-geojson-data.html
https://www.mapbox.com/ios-sdk/api/3.5.4/adding-points-to-a-map.html

> I am not clear about the performance of large GeoJSON annotations, or the difference with a source.

To be clear, RNMBGL currently supports GeoJSON as an output format when you query for rendered features, but overlays must use a [custom shape annotation format](https://github.com/mapbox/react-native-mapbox-gl/blob/master/API.md#object-shape). In current versions of the native SDKs, shape annotations have the same performance as GeoJSON sources; point annotations generally have much better performance than GeoJSON sources.

> `react-native-mapbox-gl` currently only supports adding GeoJSON, it does not expose any of the source methods

Adding GeoJSON sources to the map or changing style attributes require the runtime styling API, which is being tracked in mapbox/react-native-mapbox-gl#416. It’s a big task: implementing a natural, GL JS–like API for it would involve reverse-engineering a lot of what the native SDKs have built around the style specification.

> It seems like the only way to currently set a style is via a URL, which means that we would need a local server if we wanted offline, but we could work with an online style for now.

The native SDKs support specifying a relative URL (relative to the application bundle on iOS or the resource path on Android) or, on iOS, an absolute URL to a local temporary file. I’m unsure how well that feature works in RNMBGL.

> It looks like there is active development to be able to pass a style object

This is being tracked in mapbox/mapbox-gl-native#6386. Indeed, we’re working on some changes that’ll unblock this feature.

**Comment by sethvincent** [comment]
Thanks for this input @1ec5!

We've started using annotations and so far it's working pretty well.
